class Main {
  public static void main(String[] args) {

  //Activity 1 - Introduction
    //System.out.println(Review.sentimentVal("serene"));

  //Activity 2 - Sentiment Value and Star Ratings
    //System.out.println(Review.totalSentiment("26WestReview.txt", false,true));

  //Activity 3 - Autogenerated Review
    //System.out.println(Review.fakeReview("simpleReview.txt"));

  //Activity 4 - Create a Positive or Negative Review
    //System.out.println(Review.slantedReview("simpleReview.txt", true));

  //Activity 5 - I'm terribly sorry
    Zuck.main(20);
    //make sure your console view is wide enough

  }
}